/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidad.Vistas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import universidad.Acceso.AlumnoData;
import universidad.Acceso.InscData;
import universidad.Acceso.MateriaData;
import universidad.Entidades.*;
/**
 *
 * @author Exon
 */
public class CargarNotas extends javax.swing.JInternalFrame {

       private ArrayList<Alumnos>alist=new ArrayList<>();
       private ArrayList<Materias>mlist;
      
       private AlumnoData aldat;
       private MateriaData mateData;
       private InscData inscData;
       private DefaultTableModel tabla;
       
    public CargarNotas() {
        initComponents();
        
        aldat=new AlumnoData();
        alist=(ArrayList<Alumnos>)aldat.listarAlumnos();
        tabla=new DefaultTableModel();
        inscData=new InscData();
        mateData=new MateriaData();
        mlist=(ArrayList<Materias>)mateData.listarMaterias();

        
        cargarCombo(alist);
        armarCabecera();
        
        
        
    }
    
    private void armarCabecera(){
   
    ArrayList<Object> filacabecera=new ArrayList<>();
    filacabecera.add("ID");
    filacabecera.add("Nombre");
    filacabecera.add("Nota");
    
    for(Object it:filacabecera){
    tabla.addColumn(it);
    
    
    }
    jTabla.setModel(tabla);
    
   
   
   }
    
    
 public void cargarCombo(ArrayList<Alumnos> a){
    
        for(Alumnos al:a){
   
        jCombo.addItem(al);
    
    
    }
 }
 
  private void cleanFilaTabla(){
      int indice=tabla.getRowCount()-1;
      
      for (int i=indice;i>=0;i--){
      
      tabla.removeRow(i);
      }
        
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jModificar = new javax.swing.JButton();
        jSalir_carg_notas = new javax.swing.JButton();
        jLabelBaner = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 65, 121));

        jLabel1.setBackground(new java.awt.Color(0, 65, 121));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidad/Vistas/banerulp2.png"))); // NOI18N
        jLabel1.setText("                 Carga de Notas");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Selecciona un Alumno:");

        jCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboActionPerformed(evt);
            }
        });

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Nota"
            }
        ));
        jScrollPane1.setViewportView(jTabla);

        jModificar.setBackground(new java.awt.Color(255, 153, 0));
        jModificar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jModificar.setForeground(new java.awt.Color(255, 255, 255));
        jModificar.setText("Modificar");
        jModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModificarActionPerformed(evt);
            }
        });

        jSalir_carg_notas.setBackground(new java.awt.Color(255, 153, 0));
        jSalir_carg_notas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jSalir_carg_notas.setForeground(new java.awt.Color(255, 255, 255));
        jSalir_carg_notas.setText("Salir");
        jSalir_carg_notas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalir_carg_notasActionPerformed(evt);
            }
        });

        jLabelBaner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidad/Vistas/banerulp.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBaner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSalir_carg_notas, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSalir_carg_notas, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBaner, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalir_carg_notasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalir_carg_notasActionPerformed
       this.dispose();
    }//GEN-LAST:event_jSalir_carg_notasActionPerformed

    private void jComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboActionPerformed
      
     
        actualizar();
       
        
        
    }//GEN-LAST:event_jComboActionPerformed

    
    private void actualizar(){
    
     cleanFilaTabla();
       ArrayList<Inscripcion> inscripciones = new ArrayList<>();
        Alumnos alum = (Alumnos) jCombo.getSelectedItem();
        InscData ins = new InscData();
        Materias m=new Materias();
        MateriaData mat=new MateriaData();
        
        
        inscripciones = (ArrayList<Inscripcion>) ins.obtenerInscripcionesPorAlumno(alum.getIdAlumno());

        for(Inscripcion insc:inscripciones){
      if (alum.getIdAlumno() == insc.getIdAlumno()) {
           tabla.addRow(new Object[]{
                    insc.getIdMateria(),
                    mat.buscarNombreMateria(insc.getIdMateria()), //metodo nuevo buscar por id la materia y devuelve el string de su nombre
                   insc.getNota()});
     
               
      }}}
    
    
    
    
    
    private void jModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModificarActionPerformed
        
        InscData insc=new InscData();
        Alumnos alum = (Alumnos) jCombo.getSelectedItem();
        
        //actualizarNota(int idAlumno, int idMateria, double nota)
       // tabla.isCellEditable(WIDTH, WIDTH)
        int filaselect=jTabla.getSelectedRow();
        if(filaselect!=-1){
          double nota=Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese la nueva nota")); 
            System.out.println("entrando");
           
        Object miObjeto = tabla.getValueAt(filaselect,0);  //crear objeto vacio , darle valor
        int miEntero = (Integer) miObjeto;
          
        
           insc.actualizarNota(alum.getIdAlumno(),miEntero, nota);
           actualizar();
         
        }
    }//GEN-LAST:event_jModificarActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Alumnos> jCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBaner;
    private javax.swing.JButton jModificar;
    private javax.swing.JButton jSalir_carg_notas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabla;
    // End of variables declaration//GEN-END:variables
}
