/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidad.Vistas;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import universidad.Acceso.*;
import universidad.Entidades.*;



/**
 *
 * @author Exon
 */
public class Inscripciones extends javax.swing.JInternalFrame {

       private ArrayList<Alumnos>alist=new ArrayList<>();
       private ArrayList<Materias>mlist;
       private AlumnoData aldat;
       private MateriaData mateData;
       private InscData inscData;
       private DefaultTableModel tabla;
             
    public Inscripciones() {
        initComponents();
        
        aldat=new AlumnoData();
        alist=(ArrayList<Alumnos>)aldat.listarAlumnos();
        tabla=new DefaultTableModel();
        inscData=new InscData();
        mateData=new MateriaData();
        mlist=(ArrayList<Materias>)mateData.listarMaterias();
        
        
        cargarCombo(alist);
        armarCabecera();
    }
    
    private void cleanFilaTabla(){
      int indice=tabla.getRowCount()-1;
      
      for (int i=indice;i>=0;i--){
      
      tabla.removeRow(i);
      }
        
    }
    
    private void cargaDatosNoInscriptos(){
        //cleanFilasTable();
        Alumnos select = (Alumnos) jComboAlumnos.getSelectedItem();
        ArrayList<Materias>lista =(ArrayList<Materias>) inscData.obtenerMateriasNOCursadas(select.getIdAlumno());
        for(Materias m: lista){
            tabla.addRow(new Object [] {m.getIdMateria(), m.getNombre(), m.getAnio()});
        }
    }
    
    private void cargaDatosInscriptos(){
        //cleanFilasTable();
        Alumnos select = (Alumnos) jComboAlumnos.getSelectedItem();
        ArrayList<Materias>lista = (ArrayList<Materias>) inscData.obtenerMateriasCursadas(select.getIdAlumno());
        for(Materias m: lista){
            tabla.addRow(new Object [] {m.getIdMateria(), m.getNombre(), m.getAnio()});
        }
    }
    
    
    private void armarCabecera(){
   
    ArrayList<Object> filacabecera=new ArrayList<>();
    filacabecera.add("ID");
    filacabecera.add("Nombre");
    filacabecera.add("Año");
    
    for(Object it:filacabecera){
    tabla.addColumn(it);
    
    
    }
    jTabla.setModel(tabla);
    
   
   
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboAlumnos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jMatInsc = new javax.swing.JRadioButton();
        jBotNoInsc = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jBInscribir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSalir_insc = new javax.swing.JButton();
        jLabelBaner = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Formulario de Inscripciones");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Selecciona un Alumno:");

        jComboAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboAlumnosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Listado de Materias");

        jMatInsc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMatInsc.setForeground(new java.awt.Color(255, 153, 0));
        jMatInsc.setText("Materias Inscriptas");

        jBotNoInsc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBotNoInsc.setForeground(new java.awt.Color(255, 153, 0));
        jBotNoInsc.setText("Maternias no Inscriptas");
        jBotNoInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotNoInscActionPerformed(evt);
            }
        });

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Año"
            }
        ));
        jScrollPane1.setViewportView(jTabla);
        if (jTabla.getColumnModel().getColumnCount() > 0) {
            jTabla.getColumnModel().getColumn(0).setHeaderValue("ID");
            jTabla.getColumnModel().getColumn(1).setHeaderValue("Nombre");
            jTabla.getColumnModel().getColumn(2).setHeaderValue("Año");
        }

        jBInscribir.setBackground(new java.awt.Color(255, 153, 0));
        jBInscribir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBInscribir.setForeground(new java.awt.Color(255, 255, 255));
        jBInscribir.setText("Inscribir");
        jBInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInscribirActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Anular Inscripcion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSalir_insc.setBackground(new java.awt.Color(255, 153, 0));
        jSalir_insc.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jSalir_insc.setForeground(new java.awt.Color(255, 255, 255));
        jSalir_insc.setText("Salir");
        jSalir_insc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalir_inscActionPerformed(evt);
            }
        });

        jLabelBaner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidad/Vistas/banerulp.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBaner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(jMatInsc)
                            .addGap(122, 122, 122)
                            .addComponent(jBotNoInsc, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(jBInscribir)
                            .addGap(77, 77, 77)
                            .addComponent(jButton2)
                            .addGap(81, 81, 81)
                            .addComponent(jSalir_insc))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(187, 187, 187)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMatInsc)
                    .addComponent(jBotNoInsc))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBInscribir)
                    .addComponent(jButton2)
                    .addComponent(jSalir_insc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBaner, javax.swing.GroupLayout.PREFERRED_SIZE, 112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalir_inscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalir_inscActionPerformed
        this.dispose();
    }//GEN-LAST:event_jSalir_inscActionPerformed

    private void jComboAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboAlumnosActionPerformed
      
        
        
      
        
    }//GEN-LAST:event_jComboAlumnosActionPerformed
   
    private void jMatInscButton1formed(java.awt.event.ActionEvent evt){
        cleanFilaTabla();
        jButton2.setEnabled(false);
        jBInscribir.setEnabled(false);
        jBotNoInsc.setSelected(false);
        cargaDatosInscriptos();
        jButton2.setEnabled(true);
        jBInscribir.setEnabled(false);
    }
    
    private void jBotNoInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotNoInscActionPerformed
      cleanFilaTabla();
      jButton2.setSelected(false);
      jBInscribir.setEnabled(false);
      jMatInsc.setSelected(false); 
      cargaDatosNoInscriptos();
      jButton2.setSelected(false);
      jBInscribir.setEnabled(true);
    }//GEN-LAST:event_jBotNoInscActionPerformed

    private void jBInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInscribirActionPerformed
        int filaSeleccionada= jTabla.getSelectedRow();
        if(filaSeleccionada!=1){
            Alumnos a=(Alumnos)jComboAlumnos.getSelectedItem();
            int idMateria=(Integer)tabla.getValueAt(filaSeleccionada, 0);
            String nombreMateria=(String)tabla.getValueAt(filaSeleccionada,1);
            int anio=(Integer)tabla.getValueAt(filaSeleccionada,2);
            Materias m=new Materias(idMateria,nombreMateria,anio,true);
            
            Inscripcion i = new Inscripcion(0,a.getIdAlumno(),m.getIdMateria());        
            inscData.guardarInscripción(i);
            cleanFilaTabla();
        }        
    }//GEN-LAST:event_jBInscribirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int filaSeleccionada=jTabla.getSelectedRow();
        if(filaSeleccionada!=-1){
            Alumnos a=(Alumnos)jComboAlumnos.getSelectedItem();
            int idMateria=(Integer)tabla.getValueAt(filaSeleccionada,0);
            inscData.borrarInscripcion(a.getIdAlumno(), idMateria);
            cleanFilaTabla();
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    public void cargarCombo(ArrayList<Alumnos> a){
    
        for(Alumnos al:a){
   
    jComboAlumnos.addItem(al);
    
    
    }
    
    
    
    
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBInscribir;
    private javax.swing.JRadioButton jBotNoInsc;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<Alumnos> jComboAlumnos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBaner;
    private javax.swing.JRadioButton jMatInsc;
    private javax.swing.JButton jSalir_insc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabla;
    // End of variables declaration//GEN-END:variables
}
