/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidad.Vistas;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import universidad.Entidades.*;
import universidad.Acceso.*;

/**
 *
 * @author Exon
 */
public class ListadoAlumnosPorMateria extends javax.swing.JInternalFrame {

    private DefaultTableModel tabla;
    private InscData insc;
    private Alumnos al;
    private ArrayList<Materias>mlist=new ArrayList<>();
    private ArrayList<Alumnos>alist=new ArrayList<>();
    private Materias m;
    private MateriaData mat;
    
    
    public ListadoAlumnosPorMateria() {
    
    al=new Alumnos();
    insc=new InscData();
    tabla=new DefaultTableModel();
    m=new Materias();
    mat=new MateriaData();
    mlist=(ArrayList<Materias>) mat.listarMaterias();
    
    
        initComponents();
        cargarCombo( mlist);
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkbox1 = new java.awt.Checkbox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jCombo = new javax.swing.JComboBox<>();
        jSalir_lam = new javax.swing.JButton();
        jLabelBaner = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        checkbox1.setLabel("checkbox1");

        setBackground(new java.awt.Color(0, 65, 121));

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabla);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Seleccione una materia:");

        jCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboActionPerformed(evt);
            }
        });

        jSalir_lam.setBackground(new java.awt.Color(255, 153, 0));
        jSalir_lam.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jSalir_lam.setForeground(new java.awt.Color(255, 255, 255));
        jSalir_lam.setText("Salir");
        jSalir_lam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalir_lamActionPerformed(evt);
            }
        });

        jLabelBaner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidad/Vistas/banerulp.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidad/Vistas/banerulp2.png"))); // NOI18N
        jLabel4.setText("      Listado Alumnos por Materia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBaner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSalir_lam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(255, 255, 255))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jSalir_lam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBaner, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalir_lamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalir_lamActionPerformed
        this.dispose();
    }//GEN-LAST:event_jSalir_lamActionPerformed

    private void jComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboActionPerformed
       
        llenarTabla();
        
    }//GEN-LAST:event_jComboActionPerformed


    private void cargarCombo(ArrayList<Materias> b){
   
    
    for(Materias mD:b){
    jCombo.addItem(mD);
    
    }
    
    
    }
    
    
    
    
     private void armarCabecera(){
   
    ArrayList<Object> filacabecera=new ArrayList<>();
    filacabecera.add("ID");
    filacabecera.add("Nombre");
    filacabecera.add("Apellido");
    filacabecera.add("DNI");
    
    
    for(Object it:filacabecera){
    tabla.addColumn(it);
    
    
    }
    jTabla.setModel(tabla);
    
   
   
   }
    
    
    
    
    private void cleanFilaTabla(){
      int indice=tabla.getRowCount()-1;
      
      for (int i=indice;i>=0;i--){
      
      tabla.removeRow(i);
      }
        
    }
    
    
    
     private void llenarTabla(){
        cleanFilaTabla();
       
        m= (Materias) jCombo.getSelectedItem();
        alist = (ArrayList<Alumnos>) insc.obtenerAlumnosXMateria(m.getIdMateria());
        
        for(Alumnos a: alist){
            tabla.addRow(new Object [] {a.getIdAlumno(), a.getNombre(), a.getApellido(),a.getDni()});
        }
    }
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox checkbox1;
    private javax.swing.JComboBox<Materias> jCombo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelBaner;
    private javax.swing.JButton jSalir_lam;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabla;
    // End of variables declaration//GEN-END:variables
}
