/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidad.Vistas;

/**
 *
 * @author Exon
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jFormAlumnos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jFormMaterias = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jFromInscripciones = new javax.swing.JMenuItem();
        jFormNotas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jFormAlumxMat = new javax.swing.JMenuItem();
        jSalir_menuprincipal = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );

        jMenu1.setText("Alumno");

        jFormAlumnos.setText("Formulario de Alumno");
        jFormAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormAlumnosActionPerformed(evt);
            }
        });
        jMenu1.add(jFormAlumnos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Materia");

        jFormMaterias.setText("Formulario de Materia");
        jFormMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormMateriasActionPerformed(evt);
            }
        });
        jMenu2.add(jFormMaterias);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Administración");

        jFromInscripciones.setText("Manejo de Inscripciones");
        jFromInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFromInscripcionesActionPerformed(evt);
            }
        });
        jMenu3.add(jFromInscripciones);

        jFormNotas.setText("Manipulación de Notas");
        jFormNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormNotasActionPerformed(evt);
            }
        });
        jMenu3.add(jFormNotas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");

        jFormAlumxMat.setText("Alumnos por Materia");
        jFormAlumxMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormAlumxMatActionPerformed(evt);
            }
        });
        jMenu4.add(jFormAlumxMat);

        jMenuBar1.add(jMenu4);

        jSalir_menuprincipal.setText("Salir");
        jSalir_menuprincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSalir_menuprincipalMouseClicked(evt);
            }
        });
        jMenuBar1.add(jSalir_menuprincipal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormAlumnosActionPerformed
        
        escritorio.removeAll();
        escritorio.repaint();
        alumnos al= new alumnos();
        al.setVisible(true);
        escritorio.add(al);
        escritorio.moveToFront(al);
        
    }//GEN-LAST:event_jFormAlumnosActionPerformed

    private void jFormMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormMateriasActionPerformed
      
        escritorio.removeAll();
        escritorio.repaint();
        Materia mat= new Materia();
        mat.setVisible(true);
        escritorio.add(mat);
        escritorio.moveToFront(mat);
    }//GEN-LAST:event_jFormMateriasActionPerformed

    private void jFromInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFromInscripcionesActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        Inscripciones ins= new Inscripciones();
        ins.setVisible(true);
        escritorio.add(ins);
        escritorio.moveToFront(ins);
    }//GEN-LAST:event_jFromInscripcionesActionPerformed

    private void jFormNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormNotasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        CargarNotas car= new CargarNotas();
        car.setVisible(true);
        escritorio.add(car);
        escritorio.moveToFront(car);
    }//GEN-LAST:event_jFormNotasActionPerformed

    private void jFormAlumxMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormAlumxMatActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ListadoAlumnosPorMateria lam= new ListadoAlumnosPorMateria();
        lam.setVisible(true);
        escritorio.add(lam);
        escritorio.moveToFront(lam);
    }//GEN-LAST:event_jFormAlumxMatActionPerformed

    private void jSalir_menuprincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSalir_menuprincipalMouseClicked
       
       
        
    }//GEN-LAST:event_jSalir_menuprincipalMouseClicked

    /**
     * @param args the command line arguments
     */
public static void NimbusLookAndFeel() {
     
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
        //</editor-fold>
        menu pag=new menu();
       
       java.awt.EventQueue.invokeLater(() -> {
           new menu().setVisible(true);
        });
         
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jFormAlumnos;
    private javax.swing.JMenuItem jFormAlumxMat;
    private javax.swing.JMenuItem jFormMaterias;
    private javax.swing.JMenuItem jFormNotas;
    private javax.swing.JMenuItem jFromInscripciones;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jSalir_menuprincipal;
    // End of variables declaration//GEN-END:variables
}
