/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidad.Vistas;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import universidad.Entidades.Alumnos;
import universidad.Acceso.AlumnoData;

/**
 *
 * @author Exon
 */
public class VerAlumnos extends javax.swing.JInternalFrame {

    private DefaultTableModel tabla;
    private ArrayList<Alumnos>alist=new ArrayList<>();
    private Alumnos al;
    private AlumnoData ad;
    
    
    public VerAlumnos() {
        
        tabla=new DefaultTableModel();
        ad=new AlumnoData();
        initComponents();
        armarCabecera();
        llenarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Listado de Alumnos de la Universidad de la Punta");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universidad/Vistas/banerulp.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
     private void armarCabecera(){
   
    ArrayList<Object> filacabecera=new ArrayList<>();
    filacabecera.add("ID");
    filacabecera.add("Nombre");
    filacabecera.add("Apellido");
    filacabecera.add("DNI");
    
    
    for(Object it:filacabecera){
    tabla.addColumn(it);
    
    
    }
    jTabla.setModel(tabla);
    
   
   
   }
     
     
     
     
     
      private void cleanFilaTabla(){
      int indice=tabla.getRowCount()-1;
      
      for (int i=indice;i>=0;i--){
      
      tabla.removeRow(i);
      }
        
    }
    
    
    private void llenarTabla(){
        cleanFilaTabla();
       
        
        alist = (ArrayList<Alumnos>) ad.listarAlumnos();
        
        for(Alumnos a: alist){
            tabla.addRow(new Object [] {a.getIdAlumno(), a.getNombre(), a.getApellido(),a.getDni()});
        }
    }
      
      
      
      
      
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabla;
    // End of variables declaration//GEN-END:variables
}
